[package]
name = "example_p2p"
version = "0.1.0"
authors = ["Carlos B <carlos.baezruiz@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.13"
tokio-codec = "0.1.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rust-crypto = "^0.2"
