[package]
name = "p2p_example"
version = "0.1.0"
authors = ["Carlos B <mcflurry0@gmail.com>"]
edition = "2018"

[dependencies]

futures = "0.1"
env_logger = "0.6.0"
libp2p = "0.2.2"
tokio = "0.1"
tokio-stdin-stdout = "0.1"
