version: '3'
services:
   bot:
        build: ./bot
        working_dir: /bot
        env_file:
                - .env
   searchengine:
        image: getmeili/meilisearch
        ports:
           - 7700:7700

