version: '3'
services:
   bot:
        build: ./bot
        working_dir: /bot
        env_file:
                - .env
   searchengine:
        build: ./MeiliSearch
        ports:
           - 7700:7700

   ml_endpoint:
       build: ./ml_endpoint
       ports:
           - 5002:5002
       environment:
           - REDIS_ADDRESS=redis://redis:6379/0
           - MONGO_HOST=mongo_db
           - MONGO_Port=27017
   mongo_db:
       image: mongo:latest
       ports:
           - 27017:27017
   redis:
       image: redis:latest
       ports:
           - 6379:6379

