version: '3'
services:
  nginx:
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - ml_endpoint
   - searchengine
  bot:
        build: ./bot
        env_file:
           - .env
  searchengine:
        image: getmeili/meilisearch
        ports:
           - 7700:7700
        volumes:
           - ./data.ms:/data.ms
  ml_endpoint:
       build: ./ml_endpoint
       ports:
           - 5002:5002
       env_file:
           - .env
  web_app:
       build: ./web_app
       ports:
           - 8000:8000
       env_file:
           - .env

  mongo_db:
       image: mongo:latest
       ports:
           - 27017:27017
  redis:
       image: redis:latest
       ports:
           - 6379:6379
