version: '3'
services:
   bot:
        build: ./bot
        working_dir: /bot
        env_file:
                - .env
   searchengine:
        build: ./MeiliSearch
        ports:
           - 7700:7700

   ml_endpoint:
       build: ./ml_endpoint
       ports:
           - 5002:5002
       

